name: Deploy to production
'on':
  push:
    branches:
      - main
env: 
  VITE_PROJECT1: ${{ secrets.VITE_PROJECT1 }}
  VITE_PROJECT2: ${{ secrets.VITE_PROJECT2 }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install Dependencies
        run: npm install
      
      - name: Build example1
        run: npm run build-example1
      - name: Deploy example1
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VERSION_CONTROL_PROD }}'
          projectId: version-control-prod
          target: "example-1-prod"
          channelId: "live"
      
      - name: Build example2
        run: npm run build-example2
      - name: Deploy example2
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VERSION_CONTROL_PROD }}'
          projectId: version-control-prod
          target: "example-2-prod"
          channelId: "live"
